### ISSUE TITLE
Define shared types and interface for graders

### ISSUE THREAD

**Issue by nwalters512** [illinois/zephyr#5]
As a part of #4, we should define a common interface for graders. There's already an implicit interface in what `zephyr-catch-grader` exports, but that interface isn't shareable between graders at present.

I propose a new `@illinois/zephyr-grader-base` that defines shared types (`Grader`, `IGraderOptions`, `IScore`, `IGraderResults`, etc) that must be used by new grader implementations. These types will be based on what the Catch grader already defines.

These proposed interfaces are based on the default interfaces used by PrairieLearn to communicate test results. They're in use in many classes and have proved versatile and generic enough.

# Test cases

A grading job will produce an array of test case results.

```ts
interface ITestCaseResult {
  name: string;
  success: boolean;
  weight: number;
  earned: number;
  extraCredit?: number;
  output?: string;
  message?: string;
}
```

It may be desirable to let courses attach extra data to test cases.

# Score

A grading job will result in a score that looks like this.

```ts
interface IScore {
  totalWeight: number; // Number of available points
  totalEarned: number; // Earned points
  extraCredit: number; // Any extra credit points
  score: number; // totalEarned / totalWeight
}
```

# Grader

A grader will produce both a list of test cases and a score derived from those test cases.

Maybe we don't want them to return a score directly, but rather we can derive it from the test case results? What kind of custom logic might people want there?

```ts
interface IGraderResults {
  score: IScore;
  tests: ITestCaseResult[];
}

type Grader = (options: IGraderOptions, progressObservable?: Subject<IGraderProgress>) => Promise<IGraderResults[]>
```

The `progressObservable` is used to render real-time output to students with the student CLI. It is optional. If provided, status updates should be published to it.

**Comment by nmagerko** [comment]
I see `ITestCase` and `ITestCaseResults` mentioned in this proposal, but I don't see where the latter is used. Should the `ITestCase` type in the Grader section actually be a `ITestCaseResults`? Also, should `ITestCaseResults` be singular since it will be in an array (i.e. `ITestCaseResult`)?

Given that, I think this should be sufficient. In particular I don't think CS 241 does anything with its grading that wouldn't fit here.

**Comment by nwalters512** [comment]
Good calls - `ITestCase` is a type that was used internally by Catch but that doesn't need to be part of the public interface. Edited to address that and your other comments.

**Comment by nmagerko** [comment]
I can take this issue

**Comment by nmagerko** [comment]
Types exported in PR above
